# Your personal tweaks — edit freely (ported from your HyDE userprefs).

input {
    numlock_by_default = true
    touchpad {
        natural_scroll = no
    }
}

gestures {
    # workspace_swipe = true
}

decoration {
    inactive_opacity = 0.875
}

misc {
    # enable_swallow = true
    # swallow_regex = (kitty|foot|Alacritty)
}
